server:
  port: 8080
spring:
  application:
    name: address-book-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5008/addressbookdb
    username: addressbookadmin
    password: addressbookadmin
  liquibase:
    url: jdbc:postgresql://localhost:5008/addressbookdb
    change-log: classpath:db/changelog/db.changelog-master.yaml
    user: addressbookadmin
    password: addressbookadmin
    parameters:
      appUser: addressbookadmin
      appSchema: public
      appName: ${spring.application.name}
logging:
  level:
    org.springframework: ERROR
    com.cyberexplorer: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: addressbook.log